const SUPABASE_URL = (process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL)?.replace(/\/$/,'');
const SUPABASE_SECRET_KEY = process.env.SUPABASE_SECRET_KEY;
function requireConfig(){if(!SUPABASE_URL||!SUPABASE_SECRET_KEY)throw new Error('Konfigurasi Supabase server belum lengkap.');return {url:SUPABASE_URL,key:SUPABASE_SECRET_KEY};}
const snakeCase=(v:string)=>v.replace(/[A-Z]/g,l=>`_${l.toLowerCase()}`);
const camelCase=(v:string)=>v.replace(/_([a-z])/g,(_,l:string)=>l.toUpperCase());
const mapRow=(row:Record<string,any>)=>Object.fromEntries(Object.entries(row).map(([k,v])=>[camelCase(k),v]));
const mapPayload=(data:Record<string,any>)=>Object.fromEntries(Object.entries(data).map(([k,v])=>[snakeCase(k),v]));
const PRIMARY_KEY_MAP:Record<string,string>={teacher_profiles:'user_id',student_profiles:'user_id',workspace_invites:'code',payments:'order_id'};
const OPS:Record<string,string>={'==':'eq','>':'gt','>=':'gte','<':'lt','<=':'lte','!=':'neq'};
function filterParams(filters:[string,string,unknown][]){const p=new URLSearchParams();for(const [field,op,value] of filters)p.set(snakeCase(field),`${OPS[op]||op}.${String(value)}`);return p;}
export async function supabaseAdminRequest<T=unknown>(path:string,init:RequestInit={}){const {url,key}=requireConfig();const headers=new Headers(init.headers);headers.set('apikey',key);headers.set('Accept','application/json');if(init.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');const response=await fetch(`${url}${path}`,{...init,headers,cache:'no-store'});const text=await response.text();let data:any=null;if(text){try{data=JSON.parse(text);}catch{data=text;}}if(!response.ok)throw new Error(typeof data==='object'&&data?.message?data.message:`Supabase admin request gagal (${response.status}).`);return {data:data as T,response};}
export async function adminGetOne<T=any>(table:string,idField:string,id:string){const {data}=await supabaseAdminRequest<Record<string,any>[]>(`/rest/v1/${table}?${snakeCase(idField)}=eq.${encodeURIComponent(id)}&limit=1`);return data?.[0]?(mapRow(data[0]) as T):null;}
export async function adminSelect<T=any>(table:string,filters:[string,string,unknown][]=[]){const params=filterParams(filters);params.set('select','*');const {data}=await supabaseAdminRequest<Record<string,any>[]>(`/rest/v1/${table}?${params.toString()}`);return(data||[]).map(mapRow) as T[];}
export async function adminCount(table:string,filters:[string,string,unknown][]=[]){const params=filterParams(filters);params.set('select',PRIMARY_KEY_MAP[table]||'id');const {response}=await supabaseAdminRequest(`/rest/v1/${table}?${params.toString()}`,{headers:{Prefer:'count=exact',Range:'0-0'}});const total=Number((response.headers.get('content-range')||'').split('/')[1]);return Number.isFinite(total)?total:0;}
export async function adminUpsert(table:string,rows:Record<string,any>|Record<string,any>[]){const payload=Array.isArray(rows)?rows.map(mapPayload):mapPayload(rows);await supabaseAdminRequest(`/rest/v1/${table}`,{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(payload)});}
export async function adminUpdate(table:string,filters:[string,string,unknown][],data:Record<string,any>){const params=filterParams(filters);await supabaseAdminRequest(`/rest/v1/${table}?${params.toString()}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(mapPayload(data))});}
export async function adminDelete(table:string,filters:[string,string,unknown][]){const params=filterParams(filters);await supabaseAdminRequest(`/rest/v1/${table}?${params.toString()}`,{method:'DELETE'});}
