import { auth, storage } from '@/src/config/firebase';
import { ref, uploadBytes, uploadBytesResumable, getDownloadURL } from 'firebase/storage';
import { withTimeout } from '../utils/withTimeout';
import { userError } from '../utils/submissionRules';
import { MAX_SUBMISSION_FILES, MAX_UPLOAD_BYTES, resolveUploadContentType } from '../utils/uploadFileTypes';
export { MAX_SUBMISSION_FILES, MAX_UPLOAD_BYTES, resolveUploadContentType };
const UPLOAD_STALL_TIMEOUT_MS=30000; const UPLOAD_HARD_CEILING_MS=5*60*1000;
function uploadFileWithStallTimeout(fileRef:ReturnType<typeof ref>,file:File,contentType:string,message:string):Promise<void>{return new Promise((resolve,reject)=>{const task=uploadBytesResumable(fileRef,file,{contentType});let stallTimer:ReturnType<typeof setTimeout>;let settled=false;const finish=(fn:()=>void)=>{if(settled)return;settled=true;clearTimeout(stallTimer);clearTimeout(hardTimer);fn();};const timeoutError=()=>Object.assign(new Error(message),{userFacing:true,code:'app/timeout'});const arm=()=>{clearTimeout(stallTimer);stallTimer=setTimeout(()=>{task.cancel();finish(()=>reject(timeoutError()));},UPLOAD_STALL_TIMEOUT_MS);};const hardTimer=setTimeout(()=>{task.cancel();finish(()=>reject(timeoutError()));},UPLOAD_HARD_CEILING_MS);arm();task.on('state_changed',()=>arm(),error=>finish(()=>reject(error)),()=>finish(()=>resolve()));});}
export function validateUploadFile(file:File){if(file.size>=MAX_UPLOAD_BYTES)throw userError('Ukuran file maksimal 10 MB. Kecilkan dulu fotonya lalu coba lagi.');if(!resolveUploadContentType(file))throw userError('Format file harus gambar, PDF, atau dokumen Word.');}
function sanitizeFileName(name:string){const cleaned=name.replace(/[^a-zA-Z0-9._-]/g,'_').replace(/_+/g,'_');return cleaned.slice(-80)||'lampiran';}
export async function uploadSubmissionFile(workspaceId:string,assignmentId:string,file:File,uniquePrefix?:string){validateUploadFile(file);const uid=auth.currentUser?.uid;if(!uid)throw userError('Sesi tidak valid, coba muat ulang halaman.','unauthenticated');const fileName=sanitizeFileName(file.name);const path=`submissions/${workspaceId}/${assignmentId}/${uid}/${uniquePrefix?`${uniquePrefix}_${fileName}`:fileName}`;const fileRef=ref(storage,path);await uploadFileWithStallTimeout(fileRef,file,resolveUploadContentType(file) as string,`Unggah "${file.name}" terlalu lama, periksa koneksi internetmu lalu coba lagi.`);const url=await withTimeout(getDownloadURL(fileRef),`Gagal mengambil tautan "${file.name}", periksa koneksi internetmu lalu coba lagi.`,45000);return {fileUrl:url,fileName:file.name,filePath:path};}
export async function uploadSubmissionFiles(workspaceId:string,assignmentId:string,files:File[]){if(files.length>MAX_SUBMISSION_FILES)throw userError(`Maksimal ${MAX_SUBMISSION_FILES} file per pengumpulan.`);return Promise.all(files.map((file,index)=>uploadSubmissionFile(workspaceId,assignmentId,file,String(index))));}
export async function uploadAssignmentFile(workspaceId:string,assignmentId:string,file:File){validateUploadFile(file);const uid=auth.currentUser?.uid;if(!uid)throw userError('Sesi tidak valid, coba muat ulang halaman.','unauthenticated');const fileName=sanitizeFileName(file.name);const path=`assignment-materials/${workspaceId}/${assignmentId}/${uid}/${fileName}`;const fileRef=ref(storage,path);await uploadBytes(fileRef,file,{contentType:resolveUploadContentType(file) as string});const url=await getDownloadURL(fileRef);return {materialFileUrl:url,materialFileName:file.name,materialFilePath:path};}
